### ISSUE TITLE
Unable To Build React Native Project

### ISSUE THREAD

**Issue by AndrewHenderson** [kauffecup/react-native-web-hello-world#1]
I found this repo from [your tutorial](http://jkaufman.io/react-web-native-codesharing/). I've been unable to get the React Native side of the project building. I resolved several dependency issues and have continued to receive more. Have you attempted to build this project recently? Is it still building for you out of the box?

**Comment by AndrewHenderson** [comment]
I was getting an error message saying that [I was running `react-native` command](https://github.com/kauffecup/react-native-web-hello-world/blob/master/package.json#L6-L9), but I should instead be using `react-native-cli`, to uninstall the global `react-native` and install `react-native-cli`globally. I made along with the necessary changes to the `package.json` scripts, but then there were dependency issues.

**Comment by AndrewHenderson** [comment]
Running `react-native upgrade` seems to have resolved it.

**Comment by kauffecup** [comment]
@AndrewHenderson sorry I've been so unresponsive! this repo is a bit out of date (last commit was in january i believe) and a lot has happened since then. when i get time i'll update it to work out of the box and will close this issue when i do!

that is, however, unless you wanted to open a PR... 😄

**Comment by AndrewHenderson** [comment]
I should be able to throw together a PR quickly.

**Comment by kauffecup** [comment]
closed by #2
