### ISSUE TITLE
npm run ios-bundle has error: Unable to resolve module ReactUpdates

### ISSUE THREAD

**Issue by ngduc** [kauffecup/react-native-web-hello-world#3]
npm run ios-bundle has error: Unable to resolve module ReactUpdates

I followed this guide then it works fine.
http://stackoverflow.com/questions/40730787/unable-to-resolve-module-react-lib-reactupdates

(pinned react to: "react": "~15.3.2")
Can this be fixed? Thanks.

**Comment by ktonon** [comment]
#7

**Comment by Anima-t3d** [comment]
If you do not pin it to react 15.3.x , I had to do the following steps:

1. upgrade react-native in package.json
```json
"dependencies": {
    ...
    "react-native": "^0.42.0",
    ...
  },
```
2. run `npm install` or `yarn`

1. run `react-native upgrade` in terminal

1. Answered `y` to all (Do you want to replace ...? questions. About 10 times.)

1. make sure gradle version is updated in `android/gradle/wrapper/gradle-wrapper.properties`: changed the `distributionUrl` to `distributionUrl=https\://services.gradle.org/distributions/gradle-2.14.1-all.zip`  

1. update `index.android.js` (change the first line):
`import React, { Component, AppRegistry } from 'react-native';` to `import React, { Component } from 'react';
import { AppRegistry } from 'react-native';`

1. run `react-native run-ios` or `react-native run-android` or `npm run web-dev` to see the app working.

Anyone knows if there is actually something useful that has been overwritten? It didn't seem to be the case.

Alternatively I tried to [react-native-git-upgrade](https://facebook.github.io/react-native/docs/upgrading.html). That changed files... but then when it patched the files reverted to the state prior to the upgrade. So the errors were not resolved.
