### ISSUE TITLE
~android\app\src\main\assets\index.android.bundle no such file or directory,

### ISSUE THREAD

**Issue by Chapurin** [kauffecup/react-native-web-hello-world#4]
Hello, i do
npm run android-dev-bundle
error
ENOENT: no such file or directory, open 'C:\projets\mobweb\react-native-web-hello-world\android\app\src\main\assets\index.android.bundle'

**Comment by amoran** [comment]
What was the resolution for this?  I'm getting the same issue.

**Comment by khrizt** [comment]
I was able to solve this by creating the folder assets in that path. The problem is that the folder does not exist. Maybe it should be created, or maybe it is but as git does not add empty folders it remained in some limbo. :)
