### ISSUE TITLE
E/ReactNativeJS: Seems you're trying to access 'ReactNative.Component' from the 'react-native' package

### ISSUE THREAD

**Issue by jmuchaxo** [kauffecup/react-native-web-hello-world#8]
Hello , I keep running into this issue , have tried some fixes like remove / update some react and redux modules:  

```
E/ReactNativeJS: Seems you're trying to access 'ReactNative.Component' from the 'react-native' package. Perhaps you meant to access 'React.Component' from the 'react' package instead?

                 For example, instead of:

                   import React, { Component, View } from 'react-native';

                 You should now do:

                   import React, { Component } from 'react';
                   import { View } from 'react-native';

                 Check the release notes on how to upgrade your code - https://github.com/facebook/react-native/releases/tag/v0.25.1
```

I think this is related 
https://github.com/facebook/react-native/issues/8436
Thank you

**Comment by koutsenko** [comment]
@jmuchaxo  try this - just in index.android.js change first line:

```
import React, { Component, AppRegistry } from 'react-native';
```

to

```
import React, { Component } from 'react';
import { AppRegistry } from 'react-native';
```


It was already done in index.ios.js, seems author just forgot to change values in both entry points.

**Comment by Anima-t3d** [comment]
I fixed this in https://github.com/kauffecup/react-native-web-hello-world/pull/10

> It was already done in index.ios.js, seems author just forgot to change values in both entry points.

It's because of this commit only updating `index.ios.js`: https://github.com/kauffecup/react-native-web-hello-world/pull/2/commits/3e9a5016da97aff004767e2da16e41f981ebe612
